version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: coinexplorer-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - coinexplorer-network

volumes:
  pgadmin_data:

networks:
  coinexplorer-network:
    external: true